fragment PageSeoFragment on Page {
  PageSEO {
    SEO {
      data {
        id
        attributes {
          pageTile
          canonical
          metaRobots
          metaDescription
          keywords
        }
      }
    }
  }
}