name: aborgia

services:
  aborgia-web:
    build:
      context: .
      dockerfile: Dockerfile 
    env_file:
      .env
    ports:
      - "3000:3000"
    networks:
      - aborgia-network

networks:
  aborgia-network:
    driver: bridge
