query Pages {
  pages {
    data {
      id
      attributes {
        route
      }
    }
  }
}

query SinglePage($route: String!) {
  globalSetting {
    data {
      __typename
      attributes {
        siteName
        favicon {
          ...StrapiFile
        }
        ...StrapiThemeFragment
      }
    }
  }
  pages(filters: { route: { eq: $route } }) {
    data {
      id
      attributes {
        name
        route
        ...PageSeoFragment
      }
    }
  }
}
