/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Prototype5RouteImport } from './routes/prototype/5'
import { Route as Prototype4RouteImport } from './routes/prototype/4'
import { Route as Prototype3RouteImport } from './routes/prototype/3'
import { Route as Prototype2RouteImport } from './routes/prototype/2'
import { Route as Prototype1RouteImport } from './routes/prototype/1'

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Prototype5Route = Prototype5RouteImport.update({
  id: '/prototype/5',
  path: '/prototype/5',
  getParentRoute: () => rootRouteImport,
} as any)
const Prototype4Route = Prototype4RouteImport.update({
  id: '/prototype/4',
  path: '/prototype/4',
  getParentRoute: () => rootRouteImport,
} as any)
const Prototype3Route = Prototype3RouteImport.update({
  id: '/prototype/3',
  path: '/prototype/3',
  getParentRoute: () => rootRouteImport,
} as any)
const Prototype2Route = Prototype2RouteImport.update({
  id: '/prototype/2',
  path: '/prototype/2',
  getParentRoute: () => rootRouteImport,
} as any)
const Prototype1Route = Prototype1RouteImport.update({
  id: '/prototype/1',
  path: '/prototype/1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/prototype/1': typeof Prototype1Route
  '/prototype/2': typeof Prototype2Route
  '/prototype/3': typeof Prototype3Route
  '/prototype/4': typeof Prototype4Route
  '/prototype/5': typeof Prototype5Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/prototype/1': typeof Prototype1Route
  '/prototype/2': typeof Prototype2Route
  '/prototype/3': typeof Prototype3Route
  '/prototype/4': typeof Prototype4Route
  '/prototype/5': typeof Prototype5Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/prototype/1': typeof Prototype1Route
  '/prototype/2': typeof Prototype2Route
  '/prototype/3': typeof Prototype3Route
  '/prototype/4': typeof Prototype4Route
  '/prototype/5': typeof Prototype5Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/prototype/1'
    | '/prototype/2'
    | '/prototype/3'
    | '/prototype/4'
    | '/prototype/5'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/prototype/1'
    | '/prototype/2'
    | '/prototype/3'
    | '/prototype/4'
    | '/prototype/5'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/prototype/1'
    | '/prototype/2'
    | '/prototype/3'
    | '/prototype/4'
    | '/prototype/5'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  Prototype1Route: typeof Prototype1Route
  Prototype2Route: typeof Prototype2Route
  Prototype3Route: typeof Prototype3Route
  Prototype4Route: typeof Prototype4Route
  Prototype5Route: typeof Prototype5Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/5': {
      id: '/prototype/5'
      path: '/prototype/5'
      fullPath: '/prototype/5'
      preLoaderRoute: typeof Prototype5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/4': {
      id: '/prototype/4'
      path: '/prototype/4'
      fullPath: '/prototype/4'
      preLoaderRoute: typeof Prototype4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/3': {
      id: '/prototype/3'
      path: '/prototype/3'
      fullPath: '/prototype/3'
      preLoaderRoute: typeof Prototype3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/2': {
      id: '/prototype/2'
      path: '/prototype/2'
      fullPath: '/prototype/2'
      preLoaderRoute: typeof Prototype2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/1': {
      id: '/prototype/1'
      path: '/prototype/1'
      fullPath: '/prototype/1'
      preLoaderRoute: typeof Prototype1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  Prototype1Route: Prototype1Route,
  Prototype2Route: Prototype2Route,
  Prototype3Route: Prototype3Route,
  Prototype4Route: Prototype4Route,
  Prototype5Route: Prototype5Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
